//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeterAcquisition.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal DashboardScanStart
        {
            get
            {
                return ((decimal)(this["DashboardScanStart"]));
            }
            set
            {
                this["DashboardScanStart"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal DashboardScanEnd
        {
            get
            {
                return ((decimal)(this["DashboardScanEnd"]));
            }
            set
            {
                this["DashboardScanEnd"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HeatPumpPortName
        {
            get { return ((string)(this["HeatPumpPortName"])); }
            set { this["HeatPumpPortName"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int HeatPumpBaudRate
        {
            get { return ((int)(this["HeatPumpBaudRate"])); }
            set { this["HeatPumpBaudRate"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int HeatPumpDataBits
        {
            get { return ((int)(this["HeatPumpDataBits"])); }
            set { this["HeatPumpDataBits"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string HeatPumpParity
        {
            get { return ((string)(this["HeatPumpParity"])); }
            set { this["HeatPumpParity"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int HeatPumpStopBits
        {
            get { return ((int)(this["HeatPumpStopBits"])); }
            set { this["HeatPumpStopBits"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int HeatPumpReadTimeoutMs
        {
            get { return ((int)(this["HeatPumpReadTimeoutMs"])); }
            set { this["HeatPumpReadTimeoutMs"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int HeatPumpWriteTimeoutMs
        {
            get { return ((int)(this["HeatPumpWriteTimeoutMs"])); }
            set { this["HeatPumpWriteTimeoutMs"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int HeatPumpScanStartAddress
        {
            get { return ((int)(this["HeatPumpScanStartAddress"])); }
            set { this["HeatPumpScanStartAddress"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int HeatPumpScanEndAddress
        {
            get { return ((int)(this["HeatPumpScanEndAddress"])); }
            set { this["HeatPumpScanEndAddress"] = value; }
        }
    }
}
