/*
 Navicat Premium Data Transfer

 Source Server         : TPEM_ManagementSystem
 Source Server Type    : PostgreSQL
 Source Server Version : 180004 (180004)
 Source Host           : localhost:11451
 Source Catalog        : ma
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 180004 (180004)
 File Encoding         : 65001

 Date: 28/05/2026 16:54:07
*/


-- ----------------------------
-- Sequence structure for alarm_event_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."alarm_event_id_seq";
CREATE SEQUENCE "public"."alarm_event_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for distribution_box_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."distribution_box_id_seq";
CREATE SEQUENCE "public"."distribution_box_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for meter_comm_config_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."meter_comm_config_id_seq";
CREATE SEQUENCE "public"."meter_comm_config_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for meter_energy_history_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."meter_energy_history_id_seq";
CREATE SEQUENCE "public"."meter_energy_history_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for meter_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."meter_id_seq";
CREATE SEQUENCE "public"."meter_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for meter_power_quality_history_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."meter_power_quality_history_id_seq";
CREATE SEQUENCE "public"."meter_power_quality_history_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for meter_realtime_history_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."meter_realtime_history_id_seq";
CREATE SEQUENCE "public"."meter_realtime_history_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for mqtt_message_log_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."mqtt_message_log_id_seq";
CREATE SEQUENCE "public"."mqtt_message_log_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for site_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."site_id_seq";
CREATE SEQUENCE "public"."site_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for alarm_event
-- ----------------------------
DROP TABLE IF EXISTS "public"."alarm_event";
CREATE TABLE "public"."alarm_event" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "meter_id" int8 NOT NULL,
  "alarm_code" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "alarm_name" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "alarm_level" varchar(16) COLLATE "pg_catalog"."default" NOT NULL,
  "alarm_value" numeric(18,4),
  "threshold_value" numeric(18,4),
  "status" varchar(16) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'active'::character varying,
  "start_time" timestamptz(6) NOT NULL,
  "end_time" timestamptz(6),
  "duration_seconds" int8,
  "extra_json" jsonb,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now()
)
;

-- ----------------------------
-- Table structure for distribution_box
-- ----------------------------
DROP TABLE IF EXISTS "public"."distribution_box";
CREATE TABLE "public"."distribution_box" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "site_id" int8 NOT NULL,
  "box_code" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "box_name" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "location" varchar(255) COLLATE "pg_catalog"."default",
  "remark" varchar(255) COLLATE "pg_catalog"."default",
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now()
)
;

-- ----------------------------
-- Table structure for meter
-- ----------------------------
DROP TABLE IF EXISTS "public"."meter";
CREATE TABLE "public"."meter" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "site_id" int8 NOT NULL,
  "box_id" int8 NOT NULL,
  "meter_code" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "meter_name" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "slave_address" int4 NOT NULL,
  "serial_number" varchar(64) COLLATE "pg_catalog"."default",
  "device_type" varchar(64) COLLATE "pg_catalog"."default",
  "protocol_version" varchar(32) COLLATE "pg_catalog"."default",
  "program_version" varchar(32) COLLATE "pg_catalog"."default",
  "version_date" date,
  "location" varchar(255) COLLATE "pg_catalog"."default",
  "is_enabled" bool NOT NULL DEFAULT true,
  "is_toolbar" bool NOT NULL DEFAULT false,
  "mqtt_topic" varchar(255) COLLATE "pg_catalog"."default",
  "last_seen_time" timestamptz(6),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now()
)
;

-- ----------------------------
-- Table structure for meter_comm_config
-- ----------------------------
DROP TABLE IF EXISTS "public"."meter_comm_config";
CREATE TABLE "public"."meter_comm_config" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "meter_id" int8 NOT NULL,
  "baud_rate" int4 NOT NULL DEFAULT 9600,
  "parity" varchar(16) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'Even'::character varying,
  "stop_bits" varchar(16) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'One'::character varying,
  "data_bits" int4 NOT NULL DEFAULT 8,
  "port_name" varchar(64) COLLATE "pg_catalog"."default",
  "updated_at" timestamptz(6) NOT NULL DEFAULT now()
)
;

-- ----------------------------
-- Table structure for meter_energy_history
-- ----------------------------
DROP TABLE IF EXISTS "public"."meter_energy_history";
CREATE TABLE "public"."meter_energy_history" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "meter_id" int8 NOT NULL,
  "collect_time" timestamptz(6) NOT NULL,
  "forward_active_energy" numeric(18,4),
  "reverse_active_energy" numeric(18,4),
  "forward_reactive_energy" numeric(18,4),
  "reverse_reactive_energy" numeric(18,4)
)
;

-- ----------------------------
-- Table structure for meter_energy_latest
-- ----------------------------
DROP TABLE IF EXISTS "public"."meter_energy_latest";
CREATE TABLE "public"."meter_energy_latest" (
  "meter_id" int8 NOT NULL,
  "collect_time" timestamptz(6) NOT NULL,
  "forward_active_energy" numeric(18,4),
  "reverse_active_energy" numeric(18,4),
  "forward_reactive_energy" numeric(18,4),
  "reverse_reactive_energy" numeric(18,4),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now()
)
;

-- ----------------------------
-- Table structure for meter_power_quality_history
-- ----------------------------
DROP TABLE IF EXISTS "public"."meter_power_quality_history";
CREATE TABLE "public"."meter_power_quality_history" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "meter_id" int8 NOT NULL,
  "collect_time" timestamptz(6) NOT NULL,
  "current_thd_a" numeric(10,4),
  "current_thd_b" numeric(10,4),
  "current_thd_c" numeric(10,4),
  "voltage_thd_a" numeric(10,4),
  "voltage_thd_b" numeric(10,4),
  "voltage_thd_c" numeric(10,4),
  "voltage_unbalance" numeric(10,4),
  "current_unbalance" numeric(10,4)
)
;

-- ----------------------------
-- Table structure for meter_power_quality_latest
-- ----------------------------
DROP TABLE IF EXISTS "public"."meter_power_quality_latest";
CREATE TABLE "public"."meter_power_quality_latest" (
  "meter_id" int8 NOT NULL,
  "collect_time" timestamptz(6) NOT NULL,
  "current_thd_a" numeric(10,4),
  "current_thd_b" numeric(10,4),
  "current_thd_c" numeric(10,4),
  "voltage_thd_a" numeric(10,4),
  "voltage_thd_b" numeric(10,4),
  "voltage_thd_c" numeric(10,4),
  "voltage_unbalance" numeric(10,4),
  "current_unbalance" numeric(10,4),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now()
)
;

-- ----------------------------
-- Table structure for meter_realtime_history
-- ----------------------------
DROP TABLE IF EXISTS "public"."meter_realtime_history";
CREATE TABLE "public"."meter_realtime_history" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "meter_id" int8 NOT NULL,
  "collect_time" timestamptz(6) NOT NULL,
  "ts_minute" int8 NOT NULL,
  "voltage_a" numeric(10,3),
  "voltage_b" numeric(10,3),
  "voltage_c" numeric(10,3),
  "voltage_ab" numeric(10,3),
  "voltage_bc" numeric(10,3),
  "voltage_ca" numeric(10,3),
  "current_a" numeric(12,4),
  "current_b" numeric(12,4),
  "current_c" numeric(12,4),
  "active_power_total" numeric(14,4),
  "reactive_power_total" numeric(14,4),
  "apparent_power_total" numeric(14,4),
  "power_factor_total" numeric(8,4),
  "frequency" numeric(8,4),
  "source" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'modbus'::character varying
)
;

-- ----------------------------
-- Table structure for meter_realtime_latest
-- ----------------------------
DROP TABLE IF EXISTS "public"."meter_realtime_latest";
CREATE TABLE "public"."meter_realtime_latest" (
  "meter_id" int8 NOT NULL,
  "collect_time" timestamptz(6) NOT NULL,
  "voltage_a" numeric(10,3),
  "voltage_b" numeric(10,3),
  "voltage_c" numeric(10,3),
  "voltage_ab" numeric(10,3),
  "voltage_bc" numeric(10,3),
  "voltage_ca" numeric(10,3),
  "current_a" numeric(12,4),
  "current_b" numeric(12,4),
  "current_c" numeric(12,4),
  "active_power_total" numeric(14,4),
  "reactive_power_total" numeric(14,4),
  "apparent_power_total" numeric(14,4),
  "power_factor_total" numeric(8,4),
  "frequency" numeric(8,4),
  "data_quality" int2 NOT NULL DEFAULT 1,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now()
)
;

-- ----------------------------
-- Table structure for meter_status
-- ----------------------------
DROP TABLE IF EXISTS "public"."meter_status";
CREATE TABLE "public"."meter_status" (
  "meter_id" int8 NOT NULL,
  "is_online" bool NOT NULL DEFAULT false,
  "last_collect_time" timestamptz(6),
  "last_publish_time" timestamptz(6),
  "last_error_time" timestamptz(6),
  "last_error_message" varchar(255) COLLATE "pg_catalog"."default",
  "status_code" varchar(32) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'offline'::character varying,
  "updated_at" timestamptz(6) NOT NULL DEFAULT now()
)
;

-- ----------------------------
-- Table structure for mqtt_message_log
-- ----------------------------
DROP TABLE IF EXISTS "public"."mqtt_message_log";
CREATE TABLE "public"."mqtt_message_log" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "client_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "topic" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "qos" int2 NOT NULL DEFAULT 0,
  "payload_json" jsonb NOT NULL,
  "meter_code" varchar(64) COLLATE "pg_catalog"."default",
  "received_at" timestamptz(6) NOT NULL DEFAULT now(),
  "process_status" varchar(16) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'pending'::character varying,
  "error_message" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for site
-- ----------------------------
DROP TABLE IF EXISTS "public"."site";
CREATE TABLE "public"."site" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "site_code" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "site_name" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "address" varchar(255) COLLATE "pg_catalog"."default",
  "remark" varchar(255) COLLATE "pg_catalog"."default",
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now()
)
;

-- ----------------------------
-- Procedure structure for add_columnstore_policy
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."add_columnstore_policy"("hypertable" regclass, "after" any, "if_not_exists" bool, "schedule_interval" interval, "initial_start" timestamptz, "timezone" text, "created_before" interval);
CREATE OR REPLACE PROCEDURE "public"."add_columnstore_policy"("hypertable" regclass, "after" any=NULL::unknown, "if_not_exists" bool=false, "schedule_interval" interval=NULL::interval, "initial_start" timestamptz=NULL::timestamp with time zone, "timezone" text=NULL::text, "created_before" interval=NULL::interval)
 AS '$libdir/timescaledb-2.27.1', 'ts_policy_compression_add'
  LANGUAGE c;

-- ----------------------------
-- Function structure for add_compression_policy
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."add_compression_policy"("hypertable" regclass, "compress_after" any, "if_not_exists" bool, "schedule_interval" interval, "initial_start" timestamptz, "timezone" text, "compress_created_before" interval);
CREATE OR REPLACE FUNCTION "public"."add_compression_policy"("hypertable" regclass, "compress_after" any=NULL::unknown, "if_not_exists" bool=false, "schedule_interval" interval=NULL::interval, "initial_start" timestamptz=NULL::timestamp with time zone, "timezone" text=NULL::text, "compress_created_before" interval=NULL::interval)
  RETURNS "pg_catalog"."int4" AS '$libdir/timescaledb-2.27.1', 'ts_policy_compression_add'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for add_continuous_aggregate_policy
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."add_continuous_aggregate_policy"("continuous_aggregate" regclass, "start_offset" any, "end_offset" any, "schedule_interval" interval, "if_not_exists" bool, "initial_start" timestamptz, "timezone" text, "include_tiered_data" bool, "buckets_per_batch" int4, "max_batches_per_execution" int4, "refresh_newest_first" bool);
CREATE OR REPLACE FUNCTION "public"."add_continuous_aggregate_policy"("continuous_aggregate" regclass, "start_offset" any, "end_offset" any, "schedule_interval" interval, "if_not_exists" bool=false, "initial_start" timestamptz=NULL::timestamp with time zone, "timezone" text=NULL::text, "include_tiered_data" bool=NULL::boolean, "buckets_per_batch" int4=NULL::integer, "max_batches_per_execution" int4=NULL::integer, "refresh_newest_first" bool=NULL::boolean)
  RETURNS "pg_catalog"."int4" AS '$libdir/timescaledb-2.27.1', 'ts_policy_refresh_cagg_add'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for add_dimension
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."add_dimension"("hypertable" regclass, "column_name" name, "number_partitions" int4, "chunk_time_interval" anyelement, "partitioning_func" regproc, "if_not_exists" bool);
CREATE OR REPLACE FUNCTION "public"."add_dimension"("hypertable" regclass, "column_name" name, "number_partitions" int4=NULL::integer, "chunk_time_interval" anyelement=NULL::bigint, "partitioning_func" regproc=NULL::regproc, "if_not_exists" bool=false)
  RETURNS TABLE("dimension_id" int4, "schema_name" name, "table_name" name, "column_name" name, "created" bool) AS '$libdir/timescaledb-2.27.1', 'ts_dimension_add'
  LANGUAGE c VOLATILE
  COST 1
  ROWS 1000;

-- ----------------------------
-- Function structure for add_dimension
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."add_dimension"("hypertable" regclass, "dimension" "_timescaledb_internal"."dimension_info", "if_not_exists" bool);
CREATE OR REPLACE FUNCTION "public"."add_dimension"("hypertable" regclass, "dimension" "_timescaledb_internal"."dimension_info", "if_not_exists" bool=false)
  RETURNS TABLE("dimension_id" int4, "created" bool) AS '$libdir/timescaledb-2.27.1', 'ts_dimension_add_general'
  LANGUAGE c VOLATILE
  COST 1
  ROWS 1000;

-- ----------------------------
-- Function structure for add_job
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."add_job"("proc" regproc, "schedule_interval" interval, "config" jsonb, "initial_start" timestamptz, "scheduled" bool, "check_config" regproc, "fixed_schedule" bool, "timezone" text, "job_name" text);
CREATE OR REPLACE FUNCTION "public"."add_job"("proc" regproc, "schedule_interval" interval, "config" jsonb=NULL::jsonb, "initial_start" timestamptz=NULL::timestamp with time zone, "scheduled" bool=true, "check_config" regproc=NULL::regproc, "fixed_schedule" bool=true, "timezone" text=NULL::text, "job_name" text=NULL::text)
  RETURNS "pg_catalog"."int4" AS '$libdir/timescaledb-2.27.1', 'ts_job_add'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for add_reorder_policy
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."add_reorder_policy"("hypertable" regclass, "index_name" name, "if_not_exists" bool, "initial_start" timestamptz, "timezone" text);
CREATE OR REPLACE FUNCTION "public"."add_reorder_policy"("hypertable" regclass, "index_name" name, "if_not_exists" bool=false, "initial_start" timestamptz=NULL::timestamp with time zone, "timezone" text=NULL::text)
  RETURNS "pg_catalog"."int4" AS '$libdir/timescaledb-2.27.1', 'ts_policy_reorder_add'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for add_retention_policy
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."add_retention_policy"("relation" regclass, "drop_after" any, "if_not_exists" bool, "schedule_interval" interval, "initial_start" timestamptz, "timezone" text, "drop_created_before" interval);
CREATE OR REPLACE FUNCTION "public"."add_retention_policy"("relation" regclass, "drop_after" any=NULL::unknown, "if_not_exists" bool=false, "schedule_interval" interval=NULL::interval, "initial_start" timestamptz=NULL::timestamp with time zone, "timezone" text=NULL::text, "drop_created_before" interval=NULL::interval)
  RETURNS "pg_catalog"."int4" AS '$libdir/timescaledb-2.27.1', 'ts_policy_retention_add'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for alter_job
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."alter_job"("job_id" int4, "schedule_interval" interval, "max_runtime" interval, "max_retries" int4, "retry_period" interval, "scheduled" bool, "config" jsonb, "next_start" timestamptz, "if_exists" bool, "check_config" regproc, "fixed_schedule" bool, "initial_start" timestamptz, "timezone" text, "job_name" text);
CREATE OR REPLACE FUNCTION "public"."alter_job"("job_id" int4, "schedule_interval" interval=NULL::interval, "max_runtime" interval=NULL::interval, "max_retries" int4=NULL::integer, "retry_period" interval=NULL::interval, "scheduled" bool=NULL::boolean, "config" jsonb=NULL::jsonb, "next_start" timestamptz=NULL::timestamp with time zone, "if_exists" bool=false, "check_config" regproc=NULL::regproc, "fixed_schedule" bool=NULL::boolean, "initial_start" timestamptz=NULL::timestamp with time zone, "timezone" text=NULL::text, "job_name" text=NULL::text)
  RETURNS TABLE("job_id" int4, "schedule_interval" interval, "max_runtime" interval, "max_retries" int4, "retry_period" interval, "scheduled" bool, "config" jsonb, "next_start" timestamptz, "check_config" text, "fixed_schedule" bool, "initial_start" timestamptz, "timezone" text, "application_name" name) AS '$libdir/timescaledb-2.27.1', 'ts_job_alter'
  LANGUAGE c VOLATILE
  COST 1
  ROWS 1000;

-- ----------------------------
-- Function structure for approximate_row_count
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."approximate_row_count"("relation" regclass);
CREATE OR REPLACE FUNCTION "public"."approximate_row_count"("relation" regclass)
  RETURNS "pg_catalog"."int8" AS $BODY$
DECLARE
    v_mat_ht REGCLASS = NULL;
    v_name NAME = NULL;
    v_schema NAME = NULL;
    v_hypertable_id INTEGER;
BEGIN
    -- Check if input relation is continuous aggregate view then
    -- get the corresponding materialized hypertable and schema name
    SELECT format('%I.%I', ht.schema_name, ht.table_name)::regclass INTO v_mat_ht
      FROM pg_class c
      JOIN pg_namespace n ON (n.OID = c.relnamespace)
      JOIN _timescaledb_catalog.continuous_agg a ON (a.user_view_schema = n.nspname AND a.user_view_name = c.relname)
      JOIN _timescaledb_catalog.hypertable ht ON (a.mat_hypertable_id = ht.id)
      WHERE c.OID = relation;

    IF FOUND THEN
        relation = v_mat_ht;
    END IF;

    SELECT nspname, relname FROM pg_class c
    INNER JOIN pg_namespace n ON (n.OID = c.relnamespace)
    INTO v_schema, v_name
    WHERE c.OID = relation;

    -- for hypertables return the sum of the row counts of all chunks
    SELECT id FROM _timescaledb_catalog.hypertable INTO v_hypertable_id WHERE table_name = v_name AND schema_name = v_schema;
    IF FOUND THEN
        RETURN (SELECT coalesce(sum(_timescaledb_functions.get_approx_row_count(format('%I.%I',schema_name,table_name))),0)
          FROM _timescaledb_catalog.chunk
          WHERE hypertable_id = v_hypertable_id);
    END IF;

		IF EXISTS (SELECT FROM pg_inherits WHERE inhparent = relation) THEN
		RETURN (
        SELECT _timescaledb_functions.get_approx_row_count(relation) + COALESCE(SUM(public.approximate_row_count(i.inhrelid)),0) FROM pg_inherits i
        WHERE i.inhparent = relation
     );
    END IF;

    -- Check for input relation is Plain RELATION
    RETURN _timescaledb_functions.get_approx_row_count(relation);
END;
$BODY$
  LANGUAGE plpgsql VOLATILE STRICT
  COST 100
  SET "search_path"="pg_catalog, pg_temp";

-- ----------------------------
-- Procedure structure for attach_chunk
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."attach_chunk"("hypertable" regclass, "chunk" regclass, "slices" jsonb);
CREATE OR REPLACE PROCEDURE "public"."attach_chunk"("hypertable" regclass, "chunk" regclass, "slices" jsonb)
 AS '$libdir/timescaledb-2.27.1', 'ts_attach_chunk'
  LANGUAGE c;

-- ----------------------------
-- Function structure for attach_tablespace
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."attach_tablespace"("tablespace" name, "hypertable" regclass, "if_not_attached" bool);
CREATE OR REPLACE FUNCTION "public"."attach_tablespace"("tablespace" name, "hypertable" regclass, "if_not_attached" bool=false)
  RETURNS "pg_catalog"."void" AS '$libdir/timescaledb-2.27.1', 'ts_tablespace_attach'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for by_hash
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."by_hash"("column_name" name, "number_partitions" int4, "partition_func" regproc);
CREATE OR REPLACE FUNCTION "public"."by_hash"("column_name" name, "number_partitions" int4, "partition_func" regproc=NULL::regproc)
  RETURNS "_timescaledb_internal"."dimension_info" AS '$libdir/timescaledb-2.27.1', 'ts_hash_dimension'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for by_range
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."by_range"("column_name" name, "partition_interval" anyelement, "partition_func" regproc);
CREATE OR REPLACE FUNCTION "public"."by_range"("column_name" name, "partition_interval" anyelement=NULL::bigint, "partition_func" regproc=NULL::regproc)
  RETURNS "_timescaledb_internal"."dimension_info" AS '$libdir/timescaledb-2.27.1', 'ts_range_dimension'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for chunk_columnstore_stats
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."chunk_columnstore_stats"("hypertable" regclass);
CREATE OR REPLACE FUNCTION "public"."chunk_columnstore_stats"("hypertable" regclass)
  RETURNS TABLE("chunk_schema" name, "chunk_name" name, "compression_status" text, "before_compression_table_bytes" int8, "before_compression_index_bytes" int8, "before_compression_toast_bytes" int8, "before_compression_total_bytes" int8, "after_compression_table_bytes" int8, "after_compression_index_bytes" int8, "after_compression_toast_bytes" int8, "after_compression_total_bytes" int8, "node_name" name)
  LANGUAGE sql STABLE STRICT
  COST 100
  ROWS 1000
  SET "search_path"="pg_catalog, pg_temp"
SELECT * FROM public.chunk_compression_stats($1)
;

-- ----------------------------
-- Function structure for chunk_compression_stats
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."chunk_compression_stats"("hypertable" regclass);
CREATE OR REPLACE FUNCTION "public"."chunk_compression_stats"("hypertable" regclass)
  RETURNS TABLE("chunk_schema" name, "chunk_name" name, "compression_status" text, "before_compression_table_bytes" int8, "before_compression_index_bytes" int8, "before_compression_toast_bytes" int8, "before_compression_total_bytes" int8, "after_compression_table_bytes" int8, "after_compression_index_bytes" int8, "after_compression_toast_bytes" int8, "after_compression_total_bytes" int8, "node_name" name) AS $BODY$
DECLARE
    table_name name;
    schema_name name;
BEGIN
    SELECT
      relname, nspname
    INTO
	    table_name, schema_name
    FROM
        pg_class c
        INNER JOIN pg_namespace n ON (n.OID = c.relnamespace)
        INNER JOIN _timescaledb_catalog.hypertable ht ON (ht.schema_name = n.nspname
                AND ht.table_name = c.relname)
    WHERE
        c.OID = hypertable;

    IF table_name IS NULL THEN
	    RETURN;
	END IF;

  RETURN QUERY
  SELECT
      *,
      NULL::name
  FROM
      _timescaledb_functions.compressed_chunk_local_stats(schema_name, table_name);
END;
$BODY$
  LANGUAGE plpgsql STABLE STRICT
  COST 100
  ROWS 1000
  SET "search_path"="pg_catalog, pg_temp";

-- ----------------------------
-- Function structure for chunks_detailed_size
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."chunks_detailed_size"("hypertable" regclass);
CREATE OR REPLACE FUNCTION "public"."chunks_detailed_size"("hypertable" regclass)
  RETURNS TABLE("chunk_schema" name, "chunk_name" name, "table_bytes" int8, "index_bytes" int8, "toast_bytes" int8, "total_bytes" int8, "node_name" name) AS $BODY$
DECLARE
        table_name       NAME;
        schema_name      NAME;
BEGIN
        SELECT relname, nspname
        INTO table_name, schema_name
        FROM pg_class c
        INNER JOIN pg_namespace n ON (n.OID = c.relnamespace)
        INNER JOIN _timescaledb_catalog.hypertable ht ON (ht.schema_name = n.nspname AND ht.table_name = c.relname)
        WHERE c.OID = hypertable;

        IF table_name IS NULL THEN
            SELECT h.schema_name, h.table_name
            INTO schema_name, table_name
            FROM pg_class c
            INNER JOIN pg_namespace n ON (n.OID = c.relnamespace)
            INNER JOIN _timescaledb_catalog.continuous_agg a ON (a.user_view_schema = n.nspname AND a.user_view_name = c.relname)
            INNER JOIN _timescaledb_catalog.hypertable h ON h.id = a.mat_hypertable_id
            WHERE c.OID = hypertable;

            IF table_name IS NULL THEN
                RETURN;
            END IF;
		END IF;

    RETURN QUERY SELECT chl.chunk_schema, chl.chunk_name, chl.table_bytes, chl.index_bytes,
                        chl.toast_bytes, chl.total_bytes, NULL::NAME
            FROM _timescaledb_functions.chunks_local_size(schema_name, table_name) chl;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE STRICT
  COST 100
  ROWS 1000
  SET "search_path"="pg_catalog, pg_temp";

-- ----------------------------
-- Function structure for compress_chunk
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."compress_chunk"("uncompressed_chunk" regclass, "if_not_compressed" bool, "recompress" bool);
CREATE OR REPLACE FUNCTION "public"."compress_chunk"("uncompressed_chunk" regclass, "if_not_compressed" bool=true, "recompress" bool=false)
  RETURNS "pg_catalog"."regclass" AS '$libdir/timescaledb-2.27.1', 'ts_compress_chunk'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Procedure structure for convert_to_columnstore
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."convert_to_columnstore"("chunk" regclass, "if_not_columnstore" bool, "recompress" bool);
CREATE OR REPLACE PROCEDURE "public"."convert_to_columnstore"("chunk" regclass, "if_not_columnstore" bool=true, "recompress" bool=false)
 AS '$libdir/timescaledb-2.27.1', 'ts_compress_chunk'
  LANGUAGE c;

-- ----------------------------
-- Procedure structure for convert_to_rowstore
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."convert_to_rowstore"("chunk" regclass, "if_columnstore" bool);
CREATE OR REPLACE PROCEDURE "public"."convert_to_rowstore"("chunk" regclass, "if_columnstore" bool=true)
 AS '$libdir/timescaledb-2.27.1', 'ts_decompress_chunk'
  LANGUAGE c;

-- ----------------------------
-- Function structure for create_hypertable
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."create_hypertable"("relation" regclass, "dimension" "_timescaledb_internal"."dimension_info", "create_default_indexes" bool, "if_not_exists" bool, "migrate_data" bool);
CREATE OR REPLACE FUNCTION "public"."create_hypertable"("relation" regclass, "dimension" "_timescaledb_internal"."dimension_info", "create_default_indexes" bool=true, "if_not_exists" bool=false, "migrate_data" bool=false)
  RETURNS TABLE("hypertable_id" int4, "created" bool) AS '$libdir/timescaledb-2.27.1', 'ts_hypertable_create_general'
  LANGUAGE c VOLATILE
  COST 1
  ROWS 1000;

-- ----------------------------
-- Function structure for create_hypertable
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."create_hypertable"("relation" regclass, "time_column_name" name, "partitioning_column" name, "number_partitions" int4, "associated_schema_name" name, "associated_table_prefix" name, "chunk_time_interval" anyelement, "create_default_indexes" bool, "if_not_exists" bool, "partitioning_func" regproc, "migrate_data" bool, "chunk_target_size" text, "chunk_sizing_func" regproc, "time_partitioning_func" regproc);
CREATE OR REPLACE FUNCTION "public"."create_hypertable"("relation" regclass, "time_column_name" name, "partitioning_column" name=NULL::name, "number_partitions" int4=NULL::integer, "associated_schema_name" name=NULL::name, "associated_table_prefix" name=NULL::name, "chunk_time_interval" anyelement=NULL::bigint, "create_default_indexes" bool=true, "if_not_exists" bool=false, "partitioning_func" regproc=NULL::regproc, "migrate_data" bool=false, "chunk_target_size" text=NULL::text, "chunk_sizing_func" regproc='_timescaledb_functions.calculate_chunk_interval'::regproc, "time_partitioning_func" regproc=NULL::regproc)
  RETURNS TABLE("hypertable_id" int4, "schema_name" name, "table_name" name, "created" bool) AS '$libdir/timescaledb-2.27.1', 'ts_hypertable_create'
  LANGUAGE c VOLATILE
  COST 1
  ROWS 1000;

-- ----------------------------
-- Function structure for decompress_chunk
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."decompress_chunk"("uncompressed_chunk" regclass, "if_compressed" bool);
CREATE OR REPLACE FUNCTION "public"."decompress_chunk"("uncompressed_chunk" regclass, "if_compressed" bool=true)
  RETURNS "pg_catalog"."regclass" AS '$libdir/timescaledb-2.27.1', 'ts_decompress_chunk'
  LANGUAGE c VOLATILE STRICT
  COST 1;

-- ----------------------------
-- Function structure for delete_job
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."delete_job"("job_id" int4);
CREATE OR REPLACE FUNCTION "public"."delete_job"("job_id" int4)
  RETURNS "pg_catalog"."void" AS '$libdir/timescaledb-2.27.1', 'ts_job_delete'
  LANGUAGE c VOLATILE STRICT
  COST 1;

-- ----------------------------
-- Procedure structure for detach_chunk
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."detach_chunk"("chunk" regclass);
CREATE OR REPLACE PROCEDURE "public"."detach_chunk"("chunk" regclass)
 AS '$libdir/timescaledb-2.27.1', 'ts_detach_chunk'
  LANGUAGE c;

-- ----------------------------
-- Function structure for detach_tablespace
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."detach_tablespace"("tablespace" name, "hypertable" regclass, "if_attached" bool);
CREATE OR REPLACE FUNCTION "public"."detach_tablespace"("tablespace" name, "hypertable" regclass=NULL::regclass, "if_attached" bool=false)
  RETURNS "pg_catalog"."int4" AS '$libdir/timescaledb-2.27.1', 'ts_tablespace_detach'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for detach_tablespaces
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."detach_tablespaces"("hypertable" regclass);
CREATE OR REPLACE FUNCTION "public"."detach_tablespaces"("hypertable" regclass)
  RETURNS "pg_catalog"."int4" AS '$libdir/timescaledb-2.27.1', 'ts_tablespace_detach_all_from_hypertable'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for disable_chunk_skipping
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."disable_chunk_skipping"("hypertable" regclass, "column_name" name, "if_not_exists" bool);
CREATE OR REPLACE FUNCTION "public"."disable_chunk_skipping"("hypertable" regclass, "column_name" name, "if_not_exists" bool=false)
  RETURNS TABLE("hypertable_id" int4, "column_name" name, "disabled" bool) AS '$libdir/timescaledb-2.27.1', 'ts_chunk_column_stats_disable'
  LANGUAGE c VOLATILE
  COST 1
  ROWS 1000;

-- ----------------------------
-- Function structure for drop_chunks
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."drop_chunks"("relation" regclass, "older_than" any, "newer_than" any, "verbose" bool, "created_before" any, "created_after" any);
CREATE OR REPLACE FUNCTION "public"."drop_chunks"("relation" regclass, "older_than" any=NULL::unknown, "newer_than" any=NULL::unknown, "verbose" bool=false, "created_before" any=NULL::unknown, "created_after" any=NULL::unknown)
  RETURNS SETOF "pg_catalog"."text" AS '$libdir/timescaledb-2.27.1', 'ts_chunk_drop_chunks'
  LANGUAGE c VOLATILE
  COST 1
  ROWS 1000;

-- ----------------------------
-- Function structure for enable_chunk_skipping
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."enable_chunk_skipping"("hypertable" regclass, "column_name" name, "if_not_exists" bool);
CREATE OR REPLACE FUNCTION "public"."enable_chunk_skipping"("hypertable" regclass, "column_name" name, "if_not_exists" bool=false)
  RETURNS TABLE("column_stats_id" int4, "enabled" bool) AS '$libdir/timescaledb-2.27.1', 'ts_chunk_column_stats_enable'
  LANGUAGE c VOLATILE
  COST 1
  ROWS 1000;

-- ----------------------------
-- Function structure for generate_uuidv7
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."generate_uuidv7"();
CREATE OR REPLACE FUNCTION "public"."generate_uuidv7"()
  RETURNS "pg_catalog"."uuid" AS '$libdir/timescaledb-2.27.1', 'ts_uuid_generate_v7'
  LANGUAGE c VOLATILE STRICT
  COST 1;

-- ----------------------------
-- Function structure for get_telemetry_report
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."get_telemetry_report"();
CREATE OR REPLACE FUNCTION "public"."get_telemetry_report"()
  RETURNS "pg_catalog"."jsonb" AS '$libdir/timescaledb-2.27.1', 'ts_telemetry_get_report_jsonb'
  LANGUAGE c STABLE
  COST 1;

-- ----------------------------
-- Function structure for hypertable_approximate_detailed_size
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."hypertable_approximate_detailed_size"("relation" regclass);
CREATE OR REPLACE FUNCTION "public"."hypertable_approximate_detailed_size"("relation" regclass)
  RETURNS TABLE("table_bytes" int8, "index_bytes" int8, "toast_bytes" int8, "total_bytes" int8) AS '$libdir/timescaledb-2.27.1', 'ts_hypertable_approximate_size'
  LANGUAGE c VOLATILE
  COST 1
  ROWS 1000;

-- ----------------------------
-- Function structure for hypertable_approximate_size
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."hypertable_approximate_size"("hypertable" regclass);
CREATE OR REPLACE FUNCTION "public"."hypertable_approximate_size"("hypertable" regclass)
  RETURNS "pg_catalog"."int8"
  LANGUAGE sql VOLATILE STRICT
  COST 100
  SET "search_path"="pg_catalog, pg_temp"

   SELECT sum(total_bytes)::bigint
   FROM public.hypertable_approximate_detailed_size(hypertable);

;

-- ----------------------------
-- Function structure for hypertable_columnstore_stats
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."hypertable_columnstore_stats"("hypertable" regclass);
CREATE OR REPLACE FUNCTION "public"."hypertable_columnstore_stats"("hypertable" regclass)
  RETURNS TABLE("total_chunks" int8, "number_compressed_chunks" int8, "before_compression_table_bytes" int8, "before_compression_index_bytes" int8, "before_compression_toast_bytes" int8, "before_compression_total_bytes" int8, "after_compression_table_bytes" int8, "after_compression_index_bytes" int8, "after_compression_toast_bytes" int8, "after_compression_total_bytes" int8, "node_name" name)
  LANGUAGE sql STABLE STRICT
  COST 100
  ROWS 1000
  SET "search_path"="pg_catalog, pg_temp"
SELECT * FROM public.hypertable_compression_stats($1)
;

-- ----------------------------
-- Function structure for hypertable_compression_stats
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."hypertable_compression_stats"("hypertable" regclass);
CREATE OR REPLACE FUNCTION "public"."hypertable_compression_stats"("hypertable" regclass)
  RETURNS TABLE("total_chunks" int8, "number_compressed_chunks" int8, "before_compression_table_bytes" int8, "before_compression_index_bytes" int8, "before_compression_toast_bytes" int8, "before_compression_total_bytes" int8, "after_compression_table_bytes" int8, "after_compression_index_bytes" int8, "after_compression_toast_bytes" int8, "after_compression_total_bytes" int8, "node_name" name)
  LANGUAGE sql STABLE STRICT
  COST 100
  ROWS 1000
  SET "search_path"="pg_catalog, pg_temp"

	SELECT
        count(*)::bigint AS total_chunks,
        (count(*) FILTER (WHERE ch.compression_status = 'Compressed'))::bigint AS number_compressed_chunks,
        sum(ch.before_compression_table_bytes)::bigint AS before_compression_table_bytes,
        sum(ch.before_compression_index_bytes)::bigint AS before_compression_index_bytes,
        sum(ch.before_compression_toast_bytes)::bigint AS before_compression_toast_bytes,
        sum(ch.before_compression_total_bytes)::bigint AS before_compression_total_bytes,
        sum(ch.after_compression_table_bytes)::bigint AS after_compression_table_bytes,
        sum(ch.after_compression_index_bytes)::bigint AS after_compression_index_bytes,
        sum(ch.after_compression_toast_bytes)::bigint AS after_compression_toast_bytes,
        sum(ch.after_compression_total_bytes)::bigint AS after_compression_total_bytes,
        ch.node_name
    FROM
	    public.chunk_compression_stats(hypertable) ch
    GROUP BY
        ch.node_name;

;

-- ----------------------------
-- Function structure for hypertable_detailed_size
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."hypertable_detailed_size"("hypertable" regclass);
CREATE OR REPLACE FUNCTION "public"."hypertable_detailed_size"("hypertable" regclass)
  RETURNS TABLE("table_bytes" int8, "index_bytes" int8, "toast_bytes" int8, "total_bytes" int8, "node_name" name) AS $BODY$
DECLARE
        table_name       NAME = NULL;
        schema_name      NAME = NULL;
BEGIN
        SELECT relname, nspname
        INTO table_name, schema_name
        FROM pg_class c
        INNER JOIN pg_namespace n ON (n.OID = c.relnamespace)
        INNER JOIN _timescaledb_catalog.hypertable ht ON (ht.schema_name = n.nspname AND ht.table_name = c.relname)
        WHERE c.OID = hypertable;

        IF table_name IS NULL THEN
                SELECT h.schema_name, h.table_name
                INTO schema_name, table_name
                FROM pg_class c
                INNER JOIN pg_namespace n ON (n.OID = c.relnamespace)
                INNER JOIN _timescaledb_catalog.continuous_agg a ON (a.user_view_schema = n.nspname AND a.user_view_name = c.relname)
                INNER JOIN _timescaledb_catalog.hypertable h ON h.id = a.mat_hypertable_id
                WHERE c.OID = hypertable;

	        IF table_name IS NULL THEN
                        RETURN;
                END IF;
        END IF;

			RETURN QUERY
			SELECT *, NULL::name
			FROM _timescaledb_functions.hypertable_local_size(schema_name, table_name);
END;
$BODY$
  LANGUAGE plpgsql VOLATILE STRICT
  COST 100
  ROWS 1000
  SET "search_path"="pg_catalog, pg_temp";

-- ----------------------------
-- Function structure for hypertable_index_size
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."hypertable_index_size"("index_name" regclass);
CREATE OR REPLACE FUNCTION "public"."hypertable_index_size"("index_name" regclass)
  RETURNS "pg_catalog"."int8"
  LANGUAGE sql VOLATILE STRICT
  COST 100
  SET "search_path"="pg_catalog, pg_temp"

  SELECT
  	pg_relation_size(ht_i.indexrelid) + COALESCE(sum(pg_relation_size(ch_i.indexrelid)), 0)
  FROM pg_index ht_i
  LEFT JOIN pg_inherits ch on ch.inhparent = ht_i.indrelid
  LEFT JOIN pg_index ch_i on ch_i.indrelid = ch.inhrelid and _timescaledb_functions.index_matches(ht_i.indexrelid, ch_i.indexrelid)
  WHERE ht_i.indexrelid = index_name
  GROUP BY ht_i.indexrelid;

;

-- ----------------------------
-- Function structure for hypertable_size
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."hypertable_size"("hypertable" regclass);
CREATE OR REPLACE FUNCTION "public"."hypertable_size"("hypertable" regclass)
  RETURNS "pg_catalog"."int8"
  LANGUAGE sql VOLATILE STRICT
  COST 100
  SET "search_path"="pg_catalog, pg_temp"

   SELECT total_bytes::bigint FROM public.hypertable_detailed_size(hypertable);

;

-- ----------------------------
-- Function structure for interpolate
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."interpolate"("value" int2, "prev" record, "next" record);
CREATE OR REPLACE FUNCTION "public"."interpolate"("value" int2, "prev" record=NULL::record, "next" record=NULL::record)
  RETURNS "pg_catalog"."int2" AS '$libdir/timescaledb-2.27.1', 'ts_gapfill_marker'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for interpolate
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."interpolate"("value" int4, "prev" record, "next" record);
CREATE OR REPLACE FUNCTION "public"."interpolate"("value" int4, "prev" record=NULL::record, "next" record=NULL::record)
  RETURNS "pg_catalog"."int4" AS '$libdir/timescaledb-2.27.1', 'ts_gapfill_marker'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for interpolate
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."interpolate"("value" int8, "prev" record, "next" record);
CREATE OR REPLACE FUNCTION "public"."interpolate"("value" int8, "prev" record=NULL::record, "next" record=NULL::record)
  RETURNS "pg_catalog"."int8" AS '$libdir/timescaledb-2.27.1', 'ts_gapfill_marker'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for interpolate
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."interpolate"("value" float4, "prev" record, "next" record);
CREATE OR REPLACE FUNCTION "public"."interpolate"("value" float4, "prev" record=NULL::record, "next" record=NULL::record)
  RETURNS "pg_catalog"."float4" AS '$libdir/timescaledb-2.27.1', 'ts_gapfill_marker'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for interpolate
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."interpolate"("value" float8, "prev" record, "next" record);
CREATE OR REPLACE FUNCTION "public"."interpolate"("value" float8, "prev" record=NULL::record, "next" record=NULL::record)
  RETURNS "pg_catalog"."float8" AS '$libdir/timescaledb-2.27.1', 'ts_gapfill_marker'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for locf
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."locf"("value" anyelement, "prev" anyelement, "treat_null_as_missing" bool);
CREATE OR REPLACE FUNCTION "public"."locf"("value" anyelement, "prev" anyelement=NULL::unknown, "treat_null_as_missing" bool=false)
  RETURNS "pg_catalog"."anyelement" AS '$libdir/timescaledb-2.27.1', 'ts_gapfill_marker'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Procedure structure for merge_chunks
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."merge_chunks"("chunks" _regclass);
CREATE OR REPLACE PROCEDURE "public"."merge_chunks"("chunks" _regclass)
 AS '$libdir/timescaledb-2.27.1', 'ts_merge_chunks'
  LANGUAGE c;

-- ----------------------------
-- Procedure structure for merge_chunks
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."merge_chunks"("chunk1" regclass, "chunk2" regclass, "concurrently" bool);
CREATE OR REPLACE PROCEDURE "public"."merge_chunks"("chunk1" regclass, "chunk2" regclass, "concurrently" bool=false)
 AS '$libdir/timescaledb-2.27.1', 'ts_merge_two_chunks'
  LANGUAGE c;

-- ----------------------------
-- Procedure structure for merge_chunks_concurrently
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."merge_chunks_concurrently"("chunks" _regclass);
CREATE OR REPLACE PROCEDURE "public"."merge_chunks_concurrently"("chunks" _regclass)
 AS '$libdir/timescaledb-2.27.1', 'ts_merge_chunks_concurrently'
  LANGUAGE c;

-- ----------------------------
-- Function structure for move_chunk
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."move_chunk"("chunk" regclass, "destination_tablespace" name, "index_destination_tablespace" name, "reorder_index" regclass, "verbose" bool);
CREATE OR REPLACE FUNCTION "public"."move_chunk"("chunk" regclass, "destination_tablespace" name, "index_destination_tablespace" name=NULL::name, "reorder_index" regclass=NULL::regclass, "verbose" bool=false)
  RETURNS "pg_catalog"."void" AS '$libdir/timescaledb-2.27.1', 'ts_move_chunk'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Procedure structure for recompress_chunk
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."recompress_chunk"("chunk" regclass, "if_not_compressed" bool);
CREATE OR REPLACE PROCEDURE "public"."recompress_chunk"("chunk" regclass, "if_not_compressed" bool=true)
 AS $BODY$
BEGIN
  IF current_setting('timescaledb.enable_deprecation_warnings', true)::bool THEN
    RAISE WARNING 'procedure public.recompress_chunk(regclass,boolean) is deprecated and the functionality is now included in public.compress_chunk. this compatibility function will be removed in a future version.';
  END IF;
  PERFORM public.compress_chunk(chunk, if_not_compressed);
END$BODY$
  LANGUAGE plpgsql
  SET "search_path"="pg_catalog, pg_temp";

-- ----------------------------
-- Procedure structure for refresh_continuous_aggregate
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."refresh_continuous_aggregate"("continuous_aggregate" regclass, "window_start" any, "window_end" any, "force" bool, "options" jsonb);
CREATE OR REPLACE PROCEDURE "public"."refresh_continuous_aggregate"("continuous_aggregate" regclass, "window_start" any, "window_end" any, "force" bool=false, "options" jsonb=NULL::jsonb)
 AS '$libdir/timescaledb-2.27.1', 'ts_continuous_agg_refresh'
  LANGUAGE c;

-- ----------------------------
-- Procedure structure for remove_columnstore_policy
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."remove_columnstore_policy"("hypertable" regclass, "if_exists" bool);
CREATE OR REPLACE PROCEDURE "public"."remove_columnstore_policy"("hypertable" regclass, "if_exists" bool=false)
 AS '$libdir/timescaledb-2.27.1', 'ts_policy_compression_remove'
  LANGUAGE c;

-- ----------------------------
-- Function structure for remove_compression_policy
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."remove_compression_policy"("hypertable" regclass, "if_exists" bool);
CREATE OR REPLACE FUNCTION "public"."remove_compression_policy"("hypertable" regclass, "if_exists" bool=false)
  RETURNS "pg_catalog"."bool" AS '$libdir/timescaledb-2.27.1', 'ts_policy_compression_remove'
  LANGUAGE c VOLATILE STRICT
  COST 1;

-- ----------------------------
-- Function structure for remove_continuous_aggregate_policy
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."remove_continuous_aggregate_policy"("continuous_aggregate" regclass, "if_not_exists" bool, "if_exists" bool);
CREATE OR REPLACE FUNCTION "public"."remove_continuous_aggregate_policy"("continuous_aggregate" regclass, "if_not_exists" bool=false, "if_exists" bool=NULL::boolean)
  RETURNS "pg_catalog"."void" AS '$libdir/timescaledb-2.27.1', 'ts_policy_refresh_cagg_remove'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for remove_reorder_policy
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."remove_reorder_policy"("hypertable" regclass, "if_exists" bool);
CREATE OR REPLACE FUNCTION "public"."remove_reorder_policy"("hypertable" regclass, "if_exists" bool=false)
  RETURNS "pg_catalog"."void" AS '$libdir/timescaledb-2.27.1', 'ts_policy_reorder_remove'
  LANGUAGE c VOLATILE STRICT
  COST 1;

-- ----------------------------
-- Function structure for remove_retention_policy
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."remove_retention_policy"("relation" regclass, "if_exists" bool);
CREATE OR REPLACE FUNCTION "public"."remove_retention_policy"("relation" regclass, "if_exists" bool=false)
  RETURNS "pg_catalog"."void" AS '$libdir/timescaledb-2.27.1', 'ts_policy_retention_remove'
  LANGUAGE c VOLATILE STRICT
  COST 1;

-- ----------------------------
-- Function structure for reorder_chunk
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."reorder_chunk"("chunk" regclass, "index" regclass, "verbose" bool);
CREATE OR REPLACE FUNCTION "public"."reorder_chunk"("chunk" regclass, "index" regclass=NULL::regclass, "verbose" bool=false)
  RETURNS "pg_catalog"."void" AS '$libdir/timescaledb-2.27.1', 'ts_reorder_chunk'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Procedure structure for run_job
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."run_job"("job_id" int4);
CREATE OR REPLACE PROCEDURE "public"."run_job"("job_id" int4)
 AS '$libdir/timescaledb-2.27.1', 'ts_job_run'
  LANGUAGE c;

-- ----------------------------
-- Function structure for set_adaptive_chunking
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."set_adaptive_chunking"("hypertable" regclass, "chunk_target_size" text, INOUT "chunk_sizing_func" regproc, OUT "chunk_target_size" int8);
CREATE OR REPLACE FUNCTION "public"."set_adaptive_chunking"(IN "hypertable" regclass, IN "chunk_target_size" text, INOUT "chunk_sizing_func" regproc='_timescaledb_functions.calculate_chunk_interval'::regproc, OUT "chunk_target_size" int8)
  RETURNS "pg_catalog"."record" AS '$libdir/timescaledb-2.27.1', 'ts_chunk_adaptive_set'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for set_chunk_time_interval
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."set_chunk_time_interval"("hypertable" regclass, "chunk_time_interval" anyelement, "dimension_name" name);
CREATE OR REPLACE FUNCTION "public"."set_chunk_time_interval"("hypertable" regclass, "chunk_time_interval" anyelement, "dimension_name" name=NULL::name)
  RETURNS "pg_catalog"."void" AS '$libdir/timescaledb-2.27.1', 'ts_dimension_set_interval'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for set_integer_now_func
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."set_integer_now_func"("hypertable" regclass, "integer_now_func" regproc, "replace_if_exists" bool);
CREATE OR REPLACE FUNCTION "public"."set_integer_now_func"("hypertable" regclass, "integer_now_func" regproc, "replace_if_exists" bool=false)
  RETURNS "pg_catalog"."void" AS '$libdir/timescaledb-2.27.1', 'ts_hypertable_set_integer_now_func'
  LANGUAGE c VOLATILE STRICT
  COST 1;

-- ----------------------------
-- Function structure for set_number_partitions
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."set_number_partitions"("hypertable" regclass, "number_partitions" int4, "dimension_name" name);
CREATE OR REPLACE FUNCTION "public"."set_number_partitions"("hypertable" regclass, "number_partitions" int4, "dimension_name" name=NULL::name)
  RETURNS "pg_catalog"."void" AS '$libdir/timescaledb-2.27.1', 'ts_dimension_set_num_slices'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for set_partitioning_interval
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."set_partitioning_interval"("hypertable" regclass, "partition_interval" anyelement, "dimension_name" name);
CREATE OR REPLACE FUNCTION "public"."set_partitioning_interval"("hypertable" regclass, "partition_interval" anyelement, "dimension_name" name=NULL::name)
  RETURNS "pg_catalog"."void" AS '$libdir/timescaledb-2.27.1', 'ts_dimension_set_interval'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for set_updated_at
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."set_updated_at"();
CREATE OR REPLACE FUNCTION "public"."set_updated_at"()
  RETURNS "pg_catalog"."trigger" AS $BODY$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;

-- ----------------------------
-- Function structure for show_chunks
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."show_chunks"("relation" regclass, "older_than" any, "newer_than" any, "created_before" any, "created_after" any);
CREATE OR REPLACE FUNCTION "public"."show_chunks"("relation" regclass, "older_than" any=NULL::unknown, "newer_than" any=NULL::unknown, "created_before" any=NULL::unknown, "created_after" any=NULL::unknown)
  RETURNS SETOF "pg_catalog"."regclass" AS '$libdir/timescaledb-2.27.1', 'ts_chunk_show_chunks'
  LANGUAGE c STABLE
  COST 1
  ROWS 1000;

-- ----------------------------
-- Function structure for show_tablespaces
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."show_tablespaces"("hypertable" regclass);
CREATE OR REPLACE FUNCTION "public"."show_tablespaces"("hypertable" regclass)
  RETURNS SETOF "pg_catalog"."name" AS '$libdir/timescaledb-2.27.1', 'ts_tablespace_show'
  LANGUAGE c VOLATILE STRICT
  COST 1
  ROWS 1000;

-- ----------------------------
-- Procedure structure for split_chunk
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."split_chunk"("chunk" regclass, "split_at" any);
CREATE OR REPLACE PROCEDURE "public"."split_chunk"("chunk" regclass, "split_at" any=NULL::unknown)
 AS '$libdir/timescaledb-2.27.1', 'ts_split_chunk'
  LANGUAGE c;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" interval, "ts" uuid, "offset" interval);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" interval, "ts" uuid, "offset" interval)
  RETURNS "pg_catalog"."timestamptz" AS '$libdir/timescaledb-2.27.1', 'ts_uuid_offset_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" interval, "ts" timestamptz, "timezone" text, "origin" timestamptz, "offset" interval);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" interval, "ts" timestamptz, "timezone" text, "origin" timestamptz=NULL::timestamp with time zone, "offset" interval=NULL::interval)
  RETURNS "pg_catalog"."timestamptz" AS '$libdir/timescaledb-2.27.1', 'ts_timestamptz_timezone_bucket'
  LANGUAGE c IMMUTABLE
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" interval, "ts" uuid, "timezone" text, "origin" timestamptz, "offset" interval);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" interval, "ts" uuid, "timezone" text, "origin" timestamptz=NULL::timestamp with time zone, "offset" interval=NULL::interval)
  RETURNS "pg_catalog"."timestamptz" AS '$libdir/timescaledb-2.27.1', 'ts_uuid_timezone_bucket'
  LANGUAGE c IMMUTABLE
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" int2, "ts" int2);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" int2, "ts" int2)
  RETURNS "pg_catalog"."int2" AS '$libdir/timescaledb-2.27.1', 'ts_int16_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" int4, "ts" int4);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" int4, "ts" int4)
  RETURNS "pg_catalog"."int4" AS '$libdir/timescaledb-2.27.1', 'ts_int32_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" int8, "ts" int8);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" int8, "ts" int8)
  RETURNS "pg_catalog"."int8" AS '$libdir/timescaledb-2.27.1', 'ts_int64_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" int2, "ts" int2, "offset" int2);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" int2, "ts" int2, "offset" int2)
  RETURNS "pg_catalog"."int2" AS '$libdir/timescaledb-2.27.1', 'ts_int16_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" int4, "ts" int4, "offset" int4);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" int4, "ts" int4, "offset" int4)
  RETURNS "pg_catalog"."int4" AS '$libdir/timescaledb-2.27.1', 'ts_int32_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" int8, "ts" int8, "offset" int8);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" int8, "ts" int8, "offset" int8)
  RETURNS "pg_catalog"."int8" AS '$libdir/timescaledb-2.27.1', 'ts_int64_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" interval, "ts" date, "offset" interval);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" interval, "ts" date, "offset" interval)
  RETURNS "pg_catalog"."date" AS '$libdir/timescaledb-2.27.1', 'ts_date_offset_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" interval, "ts" timestamptz, "offset" interval);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" interval, "ts" timestamptz, "offset" interval)
  RETURNS "pg_catalog"."timestamptz" AS '$libdir/timescaledb-2.27.1', 'ts_timestamptz_offset_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" interval, "ts" timestamp, "offset" interval);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" interval, "ts" timestamp, "offset" interval)
  RETURNS "pg_catalog"."timestamp" AS '$libdir/timescaledb-2.27.1', 'ts_timestamp_offset_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" interval, "ts" uuid, "origin" timestamptz);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" interval, "ts" uuid, "origin" timestamptz)
  RETURNS "pg_catalog"."timestamptz" AS '$libdir/timescaledb-2.27.1', 'ts_uuid_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" interval, "ts" date, "origin" date);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" interval, "ts" date, "origin" date)
  RETURNS "pg_catalog"."date" AS '$libdir/timescaledb-2.27.1', 'ts_date_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" interval, "ts" timestamptz, "origin" timestamptz);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" interval, "ts" timestamptz, "origin" timestamptz)
  RETURNS "pg_catalog"."timestamptz" AS '$libdir/timescaledb-2.27.1', 'ts_timestamptz_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" interval, "ts" timestamp, "origin" timestamp);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" interval, "ts" timestamp, "origin" timestamp)
  RETURNS "pg_catalog"."timestamp" AS '$libdir/timescaledb-2.27.1', 'ts_timestamp_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" interval, "ts" uuid);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" interval, "ts" uuid)
  RETURNS "pg_catalog"."timestamptz" AS '$libdir/timescaledb-2.27.1', 'ts_uuid_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" interval, "ts" date);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" interval, "ts" date)
  RETURNS "pg_catalog"."date" AS '$libdir/timescaledb-2.27.1', 'ts_date_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" interval, "ts" timestamptz);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" interval, "ts" timestamptz)
  RETURNS "pg_catalog"."timestamptz" AS '$libdir/timescaledb-2.27.1', 'ts_timestamptz_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket"("bucket_width" interval, "ts" timestamp);
CREATE OR REPLACE FUNCTION "public"."time_bucket"("bucket_width" interval, "ts" timestamp)
  RETURNS "pg_catalog"."timestamp" AS '$libdir/timescaledb-2.27.1', 'ts_timestamp_bucket'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for time_bucket_gapfill
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket_gapfill"("bucket_width" interval, "ts" date, "start" date, "finish" date);
CREATE OR REPLACE FUNCTION "public"."time_bucket_gapfill"("bucket_width" interval, "ts" date, "start" date=NULL::date, "finish" date=NULL::date)
  RETURNS "pg_catalog"."date" AS '$libdir/timescaledb-2.27.1', 'ts_gapfill_date_bucket'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for time_bucket_gapfill
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket_gapfill"("bucket_width" int8, "ts" int8, "start" int8, "finish" int8);
CREATE OR REPLACE FUNCTION "public"."time_bucket_gapfill"("bucket_width" int8, "ts" int8, "start" int8=NULL::bigint, "finish" int8=NULL::bigint)
  RETURNS "pg_catalog"."int8" AS '$libdir/timescaledb-2.27.1', 'ts_gapfill_int64_bucket'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for time_bucket_gapfill
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket_gapfill"("bucket_width" int4, "ts" int4, "start" int4, "finish" int4);
CREATE OR REPLACE FUNCTION "public"."time_bucket_gapfill"("bucket_width" int4, "ts" int4, "start" int4=NULL::integer, "finish" int4=NULL::integer)
  RETURNS "pg_catalog"."int4" AS '$libdir/timescaledb-2.27.1', 'ts_gapfill_int32_bucket'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for time_bucket_gapfill
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket_gapfill"("bucket_width" interval, "ts" timestamptz, "timezone" text, "start" timestamptz, "finish" timestamptz);
CREATE OR REPLACE FUNCTION "public"."time_bucket_gapfill"("bucket_width" interval, "ts" timestamptz, "timezone" text, "start" timestamptz=NULL::timestamp with time zone, "finish" timestamptz=NULL::timestamp with time zone)
  RETURNS "pg_catalog"."timestamptz" AS '$libdir/timescaledb-2.27.1', 'ts_gapfill_timestamptz_timezone_bucket'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for time_bucket_gapfill
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket_gapfill"("bucket_width" interval, "ts" timestamptz, "start" timestamptz, "finish" timestamptz);
CREATE OR REPLACE FUNCTION "public"."time_bucket_gapfill"("bucket_width" interval, "ts" timestamptz, "start" timestamptz=NULL::timestamp with time zone, "finish" timestamptz=NULL::timestamp with time zone)
  RETURNS "pg_catalog"."timestamptz" AS '$libdir/timescaledb-2.27.1', 'ts_gapfill_timestamptz_bucket'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for time_bucket_gapfill
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket_gapfill"("bucket_width" interval, "ts" timestamp, "start" timestamp, "finish" timestamp);
CREATE OR REPLACE FUNCTION "public"."time_bucket_gapfill"("bucket_width" interval, "ts" timestamp, "start" timestamp=NULL::timestamp without time zone, "finish" timestamp=NULL::timestamp without time zone)
  RETURNS "pg_catalog"."timestamp" AS '$libdir/timescaledb-2.27.1', 'ts_gapfill_timestamp_bucket'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for time_bucket_gapfill
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."time_bucket_gapfill"("bucket_width" int2, "ts" int2, "start" int2, "finish" int2);
CREATE OR REPLACE FUNCTION "public"."time_bucket_gapfill"("bucket_width" int2, "ts" int2, "start" int2=NULL::smallint, "finish" int2=NULL::smallint)
  RETURNS "pg_catalog"."int2" AS '$libdir/timescaledb-2.27.1', 'ts_gapfill_int16_bucket'
  LANGUAGE c VOLATILE
  COST 1;

-- ----------------------------
-- Function structure for timescaledb_post_restore
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."timescaledb_post_restore"();
CREATE OR REPLACE FUNCTION "public"."timescaledb_post_restore"()
  RETURNS "pg_catalog"."bool" AS $BODY$
DECLARE
    db text;
    catalog_version text;
BEGIN
    SELECT m.value INTO catalog_version FROM pg_extension x
    JOIN _timescaledb_catalog.metadata m ON m.key='timescaledb_version'
    WHERE x.extname='timescaledb' AND x.extversion <> m.value;

    -- check that a loaded dump is compatible with the currently running code
    IF FOUND THEN
        RAISE EXCEPTION 'catalog version mismatch, expected "%" seen "%"', '2.27.1', catalog_version;
    END IF;

    SELECT current_database() INTO db;
    EXECUTE format($$ALTER DATABASE %I RESET timescaledb.restoring $$, db);
    -- we cannot use reset here because the reset_val might not be off
    SET timescaledb.restoring TO off;
    PERFORM _timescaledb_functions.restart_background_workers();

    RETURN true;
END
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100
  SET "search_path"="pg_catalog, pg_temp";

-- ----------------------------
-- Function structure for timescaledb_pre_restore
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."timescaledb_pre_restore"();
CREATE OR REPLACE FUNCTION "public"."timescaledb_pre_restore"()
  RETURNS "pg_catalog"."bool" AS $BODY$
DECLARE
    db text;
BEGIN
    SELECT current_database() INTO db;
    EXECUTE format($$ALTER DATABASE %I SET timescaledb.restoring ='on'$$, db);
    SET SESSION timescaledb.restoring = 'on';
    PERFORM _timescaledb_functions.stop_background_workers();
    RETURN true;
END
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100
  SET "search_path"="pg_catalog, pg_temp";

-- ----------------------------
-- Function structure for to_uuidv7
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."to_uuidv7"("ts" timestamptz);
CREATE OR REPLACE FUNCTION "public"."to_uuidv7"("ts" timestamptz)
  RETURNS "pg_catalog"."uuid" AS '$libdir/timescaledb-2.27.1', 'ts_uuid_v7_from_timestamptz'
  LANGUAGE c VOLATILE STRICT
  COST 1;

-- ----------------------------
-- Function structure for to_uuidv7_boundary
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."to_uuidv7_boundary"("ts" timestamptz);
CREATE OR REPLACE FUNCTION "public"."to_uuidv7_boundary"("ts" timestamptz)
  RETURNS "pg_catalog"."uuid" AS '$libdir/timescaledb-2.27.1', 'ts_uuid_v7_from_timestamptz_boundary'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for uuid_timestamp
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."uuid_timestamp"("uuid" uuid);
CREATE OR REPLACE FUNCTION "public"."uuid_timestamp"("uuid" uuid)
  RETURNS "pg_catalog"."timestamptz" AS '$libdir/timescaledb-2.27.1', 'ts_timestamptz_from_uuid_v7'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for uuid_timestamp_micros
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."uuid_timestamp_micros"("uuid" uuid);
CREATE OR REPLACE FUNCTION "public"."uuid_timestamp_micros"("uuid" uuid)
  RETURNS "pg_catalog"."timestamptz" AS '$libdir/timescaledb-2.27.1', 'ts_timestamptz_from_uuid_v7_with_microseconds'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Function structure for uuid_version
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."uuid_version"("uuid" uuid);
CREATE OR REPLACE FUNCTION "public"."uuid_version"("uuid" uuid)
  RETURNS "pg_catalog"."int4" AS '$libdir/timescaledb-2.27.1', 'ts_uuid_version'
  LANGUAGE c IMMUTABLE STRICT
  COST 1;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."alarm_event_id_seq"
OWNED BY "public"."alarm_event"."id";
SELECT setval('"public"."alarm_event_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."distribution_box_id_seq"
OWNED BY "public"."distribution_box"."id";
SELECT setval('"public"."distribution_box_id_seq"', 4, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."meter_comm_config_id_seq"
OWNED BY "public"."meter_comm_config"."id";
SELECT setval('"public"."meter_comm_config_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."meter_energy_history_id_seq"
OWNED BY "public"."meter_energy_history"."id";
SELECT setval('"public"."meter_energy_history_id_seq"', 163, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."meter_id_seq"
OWNED BY "public"."meter"."id";
SELECT setval('"public"."meter_id_seq"', 4, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."meter_power_quality_history_id_seq"
OWNED BY "public"."meter_power_quality_history"."id";
SELECT setval('"public"."meter_power_quality_history_id_seq"', 163, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."meter_realtime_history_id_seq"
OWNED BY "public"."meter_realtime_history"."id";
SELECT setval('"public"."meter_realtime_history_id_seq"', 163, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."mqtt_message_log_id_seq"
OWNED BY "public"."mqtt_message_log"."id";
SELECT setval('"public"."mqtt_message_log_id_seq"', 167, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."site_id_seq"
OWNED BY "public"."site"."id";
SELECT setval('"public"."site_id_seq"', 4, true);

-- ----------------------------
-- Indexes structure for table alarm_event
-- ----------------------------
CREATE INDEX "idx_alarm_event_meter_status_time" ON "public"."alarm_event" USING btree (
  "meter_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
  "status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "start_time" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
);
CREATE INDEX "idx_alarm_event_start_time" ON "public"."alarm_event" USING btree (
  "start_time" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
);

-- ----------------------------
-- Triggers structure for table alarm_event
-- ----------------------------
CREATE TRIGGER "trg_alarm_event_updated_at" BEFORE UPDATE ON "public"."alarm_event"
FOR EACH ROW
EXECUTE PROCEDURE "public"."set_updated_at"();

-- ----------------------------
-- Primary Key structure for table alarm_event
-- ----------------------------
ALTER TABLE "public"."alarm_event" ADD CONSTRAINT "alarm_event_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Triggers structure for table distribution_box
-- ----------------------------
CREATE TRIGGER "trg_distribution_box_updated_at" BEFORE UPDATE ON "public"."distribution_box"
FOR EACH ROW
EXECUTE PROCEDURE "public"."set_updated_at"();

-- ----------------------------
-- Uniques structure for table distribution_box
-- ----------------------------
ALTER TABLE "public"."distribution_box" ADD CONSTRAINT "uk_site_box" UNIQUE ("site_id", "box_code");

-- ----------------------------
-- Primary Key structure for table distribution_box
-- ----------------------------
ALTER TABLE "public"."distribution_box" ADD CONSTRAINT "distribution_box_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Triggers structure for table meter
-- ----------------------------
CREATE TRIGGER "trg_meter_updated_at" BEFORE UPDATE ON "public"."meter"
FOR EACH ROW
EXECUTE PROCEDURE "public"."set_updated_at"();

-- ----------------------------
-- Uniques structure for table meter
-- ----------------------------
ALTER TABLE "public"."meter" ADD CONSTRAINT "uk_site_meter" UNIQUE ("site_id", "meter_code");
ALTER TABLE "public"."meter" ADD CONSTRAINT "uk_box_slave" UNIQUE ("box_id", "slave_address");

-- ----------------------------
-- Primary Key structure for table meter
-- ----------------------------
ALTER TABLE "public"."meter" ADD CONSTRAINT "meter_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Triggers structure for table meter_comm_config
-- ----------------------------
CREATE TRIGGER "trg_meter_comm_config_updated_at" BEFORE UPDATE ON "public"."meter_comm_config"
FOR EACH ROW
EXECUTE PROCEDURE "public"."set_updated_at"();

-- ----------------------------
-- Uniques structure for table meter_comm_config
-- ----------------------------
ALTER TABLE "public"."meter_comm_config" ADD CONSTRAINT "uk_meter_comm" UNIQUE ("meter_id");

-- ----------------------------
-- Primary Key structure for table meter_comm_config
-- ----------------------------
ALTER TABLE "public"."meter_comm_config" ADD CONSTRAINT "meter_comm_config_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table meter_energy_history
-- ----------------------------
CREATE INDEX "idx_meter_energy_history_meter_time" ON "public"."meter_energy_history" USING btree (
  "meter_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
  "collect_time" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
);
CREATE INDEX "meter_energy_history_collect_time_idx" ON "public"."meter_energy_history" USING btree (
  "collect_time" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
);
CREATE UNIQUE INDEX "uq_meter_energy_history_meter_time" ON "public"."meter_energy_history" USING btree (
  "meter_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
  "collect_time" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table meter_energy_history
-- ----------------------------
ALTER TABLE "public"."meter_energy_history" ADD CONSTRAINT "pk_meter_energy_history" PRIMARY KEY ("collect_time", "id");

-- ----------------------------
-- Triggers structure for table meter_energy_latest
-- ----------------------------
CREATE TRIGGER "trg_meter_energy_latest_updated_at" BEFORE UPDATE ON "public"."meter_energy_latest"
FOR EACH ROW
EXECUTE PROCEDURE "public"."set_updated_at"();

-- ----------------------------
-- Primary Key structure for table meter_energy_latest
-- ----------------------------
ALTER TABLE "public"."meter_energy_latest" ADD CONSTRAINT "meter_energy_latest_pkey" PRIMARY KEY ("meter_id");

-- ----------------------------
-- Indexes structure for table meter_power_quality_history
-- ----------------------------
CREATE INDEX "idx_meter_power_quality_history_meter_time" ON "public"."meter_power_quality_history" USING btree (
  "meter_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
  "collect_time" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
);
CREATE INDEX "meter_power_quality_history_collect_time_idx" ON "public"."meter_power_quality_history" USING btree (
  "collect_time" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
);
CREATE UNIQUE INDEX "uq_meter_power_quality_history_meter_time" ON "public"."meter_power_quality_history" USING btree (
  "meter_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
  "collect_time" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table meter_power_quality_history
-- ----------------------------
ALTER TABLE "public"."meter_power_quality_history" ADD CONSTRAINT "pk_meter_power_quality_history" PRIMARY KEY ("collect_time", "id");

-- ----------------------------
-- Triggers structure for table meter_power_quality_latest
-- ----------------------------
CREATE TRIGGER "trg_meter_power_quality_latest_updated_at" BEFORE UPDATE ON "public"."meter_power_quality_latest"
FOR EACH ROW
EXECUTE PROCEDURE "public"."set_updated_at"();

-- ----------------------------
-- Primary Key structure for table meter_power_quality_latest
-- ----------------------------
ALTER TABLE "public"."meter_power_quality_latest" ADD CONSTRAINT "meter_power_quality_latest_pkey" PRIMARY KEY ("meter_id");

-- ----------------------------
-- Indexes structure for table meter_realtime_history
-- ----------------------------
CREATE INDEX "idx_meter_realtime_history_meter_time" ON "public"."meter_realtime_history" USING btree (
  "meter_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
  "collect_time" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
);
CREATE INDEX "idx_meter_realtime_history_time" ON "public"."meter_realtime_history" USING btree (
  "collect_time" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
);
CREATE INDEX "meter_realtime_history_collect_time_idx" ON "public"."meter_realtime_history" USING btree (
  "collect_time" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
);
CREATE UNIQUE INDEX "uq_meter_realtime_history_meter_time" ON "public"."meter_realtime_history" USING btree (
  "meter_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
  "collect_time" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table meter_realtime_history
-- ----------------------------
ALTER TABLE "public"."meter_realtime_history" ADD CONSTRAINT "pk_meter_realtime_history" PRIMARY KEY ("collect_time", "id");

-- ----------------------------
-- Triggers structure for table meter_realtime_latest
-- ----------------------------
CREATE TRIGGER "trg_meter_realtime_latest_updated_at" BEFORE UPDATE ON "public"."meter_realtime_latest"
FOR EACH ROW
EXECUTE PROCEDURE "public"."set_updated_at"();

-- ----------------------------
-- Primary Key structure for table meter_realtime_latest
-- ----------------------------
ALTER TABLE "public"."meter_realtime_latest" ADD CONSTRAINT "meter_realtime_latest_pkey" PRIMARY KEY ("meter_id");

-- ----------------------------
-- Triggers structure for table meter_status
-- ----------------------------
CREATE TRIGGER "trg_meter_status_updated_at" BEFORE UPDATE ON "public"."meter_status"
FOR EACH ROW
EXECUTE PROCEDURE "public"."set_updated_at"();

-- ----------------------------
-- Primary Key structure for table meter_status
-- ----------------------------
ALTER TABLE "public"."meter_status" ADD CONSTRAINT "meter_status_pkey" PRIMARY KEY ("meter_id");

-- ----------------------------
-- Indexes structure for table mqtt_message_log
-- ----------------------------
CREATE INDEX "idx_mqtt_message_log_meter_time" ON "public"."mqtt_message_log" USING btree (
  "meter_code" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "received_at" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
);
CREATE INDEX "idx_mqtt_message_log_status_time" ON "public"."mqtt_message_log" USING btree (
  "process_status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "received_at" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
);
CREATE INDEX "idx_mqtt_message_log_topic_time" ON "public"."mqtt_message_log" USING btree (
  "topic" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "received_at" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
);

-- ----------------------------
-- Primary Key structure for table mqtt_message_log
-- ----------------------------
ALTER TABLE "public"."mqtt_message_log" ADD CONSTRAINT "mqtt_message_log_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Triggers structure for table site
-- ----------------------------
CREATE TRIGGER "trg_site_updated_at" BEFORE UPDATE ON "public"."site"
FOR EACH ROW
EXECUTE PROCEDURE "public"."set_updated_at"();

-- ----------------------------
-- Uniques structure for table site
-- ----------------------------
ALTER TABLE "public"."site" ADD CONSTRAINT "site_site_code_key" UNIQUE ("site_code");

-- ----------------------------
-- Primary Key structure for table site
-- ----------------------------
ALTER TABLE "public"."site" ADD CONSTRAINT "site_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table alarm_event
-- ----------------------------
ALTER TABLE "public"."alarm_event" ADD CONSTRAINT "fk_alarm_meter" FOREIGN KEY ("meter_id") REFERENCES "public"."meter" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table distribution_box
-- ----------------------------
ALTER TABLE "public"."distribution_box" ADD CONSTRAINT "fk_box_site" FOREIGN KEY ("site_id") REFERENCES "public"."site" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table meter
-- ----------------------------
ALTER TABLE "public"."meter" ADD CONSTRAINT "fk_meter_box" FOREIGN KEY ("box_id") REFERENCES "public"."distribution_box" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "public"."meter" ADD CONSTRAINT "fk_meter_site" FOREIGN KEY ("site_id") REFERENCES "public"."site" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table meter_comm_config
-- ----------------------------
ALTER TABLE "public"."meter_comm_config" ADD CONSTRAINT "fk_comm_meter" FOREIGN KEY ("meter_id") REFERENCES "public"."meter" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table meter_energy_history
-- ----------------------------
ALTER TABLE "public"."meter_energy_history" ADD CONSTRAINT "fk_meter_energy_history_meter" FOREIGN KEY ("meter_id") REFERENCES "public"."meter" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table meter_energy_latest
-- ----------------------------
ALTER TABLE "public"."meter_energy_latest" ADD CONSTRAINT "fk_energy_latest_meter" FOREIGN KEY ("meter_id") REFERENCES "public"."meter" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table meter_power_quality_history
-- ----------------------------
ALTER TABLE "public"."meter_power_quality_history" ADD CONSTRAINT "fk_meter_power_quality_history_meter" FOREIGN KEY ("meter_id") REFERENCES "public"."meter" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table meter_power_quality_latest
-- ----------------------------
ALTER TABLE "public"."meter_power_quality_latest" ADD CONSTRAINT "fk_quality_latest_meter" FOREIGN KEY ("meter_id") REFERENCES "public"."meter" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table meter_realtime_history
-- ----------------------------
ALTER TABLE "public"."meter_realtime_history" ADD CONSTRAINT "fk_meter_realtime_history_meter" FOREIGN KEY ("meter_id") REFERENCES "public"."meter" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table meter_realtime_latest
-- ----------------------------
ALTER TABLE "public"."meter_realtime_latest" ADD CONSTRAINT "fk_realtime_latest_meter" FOREIGN KEY ("meter_id") REFERENCES "public"."meter" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table meter_status
-- ----------------------------
ALTER TABLE "public"."meter_status" ADD CONSTRAINT "fk_status_meter" FOREIGN KEY ("meter_id") REFERENCES "public"."meter" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
